version: '3'

services:
    db:
      image: postgres
      container_name: plexxis-db
      expose:
        - 5432
      environment:
        POSTGRES_USER: plexxis
        POSTGRES_PASSWORD: password1234
        POSTGRES_DB: plexxis
      ports:
        - "5432:5432"
